from falcor import *

def render_graph_DefaultRenderGraph():
    g = RenderGraph('DefaultRenderGraph')
    loadRenderPassLibrary('BSDFViewer.dll')
    loadRenderPassLibrary('AccumulatePass.dll')
    loadRenderPassLibrary('TemporalDelayPass.dll')
    loadRenderPassLibrary('Antialiasing.dll')
    loadRenderPassLibrary('SSAO.dll')
    loadRenderPassLibrary('DenoiserRenderPass.dll')
    loadRenderPassLibrary('BlitPass.dll')
    loadRenderPassLibrary('CSM.dll')
    loadRenderPassLibrary('DebugPasses.dll')
    loadRenderPassLibrary('DepthPass.dll')
    loadRenderPassLibrary('ErrorMeasurePass.dll')
    loadRenderPassLibrary('WhittedRayTracer.dll')
    loadRenderPassLibrary('ForwardLightingPass.dll')
    loadRenderPassLibrary('GBuffer.dll')
    loadRenderPassLibrary('ImageLoader.dll')
    loadRenderPassLibrary('MegakernelPathTracer.dll')
    loadRenderPassLibrary('MinimalPathTracer.dll')
    loadRenderPassLibrary('PlecoBilateralPass.dll')
    loadRenderPassLibrary('PassLibraryTemplate.dll')
    loadRenderPassLibrary('PixelInspectorPass.dll')
    loadRenderPassLibrary('PlecoDenoiser.dll')
    loadRenderPassLibrary('PlecoRayTracer.dll')
    loadRenderPassLibrary('PlecoTemporalPass.dll')
    loadRenderPassLibrary('SceneDebugger.dll')
    loadRenderPassLibrary('SkyBox.dll')
    loadRenderPassLibrary('SVGFPass.dll')
    loadRenderPassLibrary('ToneMapper.dll')
    loadRenderPassLibrary('Utils.dll')
    PlecoRayTracer = createPass('PlecoRayTracer')
    g.addPass(PlecoRayTracer, 'PlecoRayTracer')
    SideBySidePass_ = createPass('SideBySidePass', {'splitLocation': -1.0, 'showTextLabels': False, 'leftLabel': 'Left side', 'rightLabel': 'Right side'})
    g.addPass(SideBySidePass_, 'SideBySidePass_')
    GBufferRT = createPass('GBufferRT', {'samplePattern': SamplePattern.Center, 'sampleCount': 16, 'disableAlphaTest': False, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': CullMode.CullBack, 'texLOD': LODMode.UseMip0})
    g.addPass(GBufferRT, 'GBufferRT')
    PlecoTemporalPass_ = createPass('PlecoTemporalPass')
    g.addPass(PlecoTemporalPass_, 'PlecoTemporalPass_')
    PlecoBilateralPass_ = createPass('PlecoBilateralPass')
    g.addPass(PlecoBilateralPass_, 'PlecoBilateralPass_')
    PlecoTemporalPass__ = createPass('PlecoTemporalPass')
    g.addPass(PlecoTemporalPass__, 'PlecoTemporalPass__')
    g.addEdge('GBufferRT.posW', 'PlecoRayTracer.iWorldPosition')
    g.addEdge('GBufferRT.normW', 'PlecoRayTracer.iWorldNormal')
    g.addEdge('GBufferRT.diffuseOpacity', 'PlecoRayTracer.iMaterialDiffuse')
    g.addEdge('GBufferRT.specRough', 'PlecoRayTracer.iMaterialSpecRough')
    g.addEdge('GBufferRT.emissive', 'PlecoRayTracer.iMaterialEmissive')
    g.addEdge('GBufferRT.matlExtra', 'PlecoRayTracer.iMaterialExtraParams')
    g.addEdge('PlecoTemporalPass_.Output_From_PD', 'PlecoBilateralPass_.Input_From_PlecoRT')
    g.addEdge('PlecoRayTracer.oColor', 'PlecoTemporalPass_.Input_From_PlecoRT')
    g.addEdge('PlecoRayTracer.oColor', 'SideBySidePass_.leftInput')
    g.addEdge('PlecoTemporalPass__.Output_From_PD', 'SideBySidePass_.rightInput')
    g.addEdge('PlecoBilateralPass_.Output_From_PD', 'PlecoTemporalPass__.Input_From_PlecoRT')
    g.markOutput('SideBySidePass_.output')
    return g

DefaultRenderGraph = render_graph_DefaultRenderGraph()
try: m.addGraph(DefaultRenderGraph)
except NameError: None
